on:
  push:
    branches: [main]

permissions:
  contents: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: true
      - name: build
        run: pnpm build
      - name: gh pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrects.GITHUB_TOKEN }}
          publish_dir: dist
